package com.mtriet.tamlottery.common.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    INVALID_STATE,
    INVALID_REQUEST,
    INVALID_RETURN_PARTIES,
    INVENTORY_NOT_ENOUGH,
    RETURN_EXCEEDS_ALLOCATION,
    ADJUSTMENT_EXCEEDS_INVENTORY,
    UNAPPROVED_ADJUSTMENT,
    PENDING_CASH_TRANSACTION,
    RECONCILIATION_ALREADY_EXISTS,
    RECONCILIATION_REQUIRES_REVIEW,
    SELLER_RECONCILIATION_REQUIRED,
    VERSION_CONFLICT,
    UNAUTHORIZED,
    FORBIDDEN
}

